### ISSUE TITLE
streaming example: help required

### ISSUE THREAD

**Issue by markdoerr** [socotecio/django-socio-grpc-example#9]
@AMontagu and @legau,
I added [streaming examples](https://github.com/socotecio/django-socio-grpc-example/blob/feature/async_example_bibliography/backend/example_bib_app/services.py): The first one should stream all books (in stead of a list), the second one should use two-directional streaming as in the original example of @AMontagu.  

Could you please check, if the code looks correct ? 
Could you please draft, how a client for the first example looks like ?
(I guess for the second one I need the queuing, like you did it in the old questionstream example, @AMontagu ?)
Merci

**Comment by AMontagu** [comment]
Hi @markdoerr 
I reviewed directly on the MR
Let's talk about it in the MR

**Comment by markdoerr** [comment]
:+1:
